---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevious-backend.fullname" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-backend.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "kubevious-backend.fullname" . }}
      {{- include "kubevious.match-labels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "kubevious-backend.fullname" . }}
        {{- include "kubevious.labels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "{{ .Values.backend.log.level }}"
            - name: SERVER_PORT
              value: "4001"
            - name: COLLECTOR_BASE_URL
              value: {{ include "kubevious-collector.baseUrl" . }}
            - name: PARSER_BASE_URL
              value: {{ include "kubevious-parser.baseUrl" . }}
            - name: GUARD_BASE_URL
              value: {{ include "kubevious-guard.baseUrl" . }}
          envFrom:
            - configMapRef:
                name: {{ include "kubevious-mysql.config" . }}
            - secretRef:
                name: {{ include "kubevious-mysql.secret" . }}
            - configMapRef:
                name: {{ include "kubevious-redis.config" . }}
            - secretRef:
                name: {{ include "kubevious-worldvious.secret" . }}
            - configMapRef:
                name: {{ include "kubevious-worldvious.config" . }}
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      serviceAccountName: {{ include "kubevious-backend.serviceAccountName" . }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
