apiVersion: v2
description: Elastic Beats managed by the ECK operator
icon: https://helm.elastic.co/icons/beats.png
kubeVersion: '>= 1.20.0-0'
name: eck-beats
sources:
- https://github.com/elastic/cloud-on-k8s
- https://github.com/elastic/beats
type: application
version: 0.16.0
