# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: kai.scheduler/v1
kind: Config
metadata:
  name: kai-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  namespace: {{ .Release.Namespace }}
  global:
    {{- if .Values.global.namespaceLabelSelector }}
    namespaceLabelSelector:
      {{- toYaml .Values.global.namespaceLabelSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.global.podLabelSelector }}
    podLabelSelector:
      {{- toYaml .Values.global.podLabelSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.global.affinity }}
    affinity:
      {{- toYaml .Values.global.affinity | nindent 6 }}
    {{- end }}
    {{- if .Values.global.requireDefaultPodAntiAffinityTerm }}
    requireDefaultPodAntiAffinityTerm: true
    {{- end }}
    {{- if .Values.global.tolerations }}
    tolerations:
      {{- toYaml .Values.global.tolerations | nindent 6 }}
    {{- end }}
    {{- if .Values.global.securityContext }}
    securityContext:
      {{- toYaml .Values.global.securityContext | nindent 6 }}
    {{- end }}
    {{- if .Values.global.imagePullSecrets }}
    imagesPullSecret: {{ index .Values.global.imagePullSecrets 0 | default "" }}
    {{- end }}
    replicaCount: {{ .Values.operator.replicaCount | default 1 }}

  binder:
    service:
      enabled: true
      image:
        name: {{ .Values.binder.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.binder.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.binder.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.binder.resources }}
      resources:
        {{- toYaml .Values.binder.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.binder.affinity }}
      affinity:
        {{- toYaml .Values.binder.affinity | nindent 8 }}
      {{- end }}
    metricsPort: {{ .Values.binder.ports.metricsPort }}
    resourceReservation:
      {{- if .Values.binder.runtimeClassName }}
      runtimeClassName: {{ .Values.binder.runtimeClassName }}
      {{- end }}
      image:
        name: {{ .Values.binder.resourceReservationImage.name }}
      {{- if .Values.binder.resourceReservationPodResources }}
      podResources:
        {{- toYaml .Values.binder.resourceReservationPodResources | nindent 8 }}
      {{- end }}

  podGroupController:
    service:
      enabled: true
      image:
        name: {{ .Values.podgroupcontroller.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.podgroupcontroller.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.podgroupcontroller.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.podgroupcontroller.resources }}
      resources:
        {{- toYaml .Values.podgroupcontroller.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.podgroupcontroller.affinity }}
      affinity:
        {{- toYaml .Values.podgroupcontroller.affinity | nindent 8 }}
      {{- end }}

  queueController:
    service:
      enabled: true
      image:
        name: {{ .Values.queuecontroller.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.queuecontroller.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.queuecontroller.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.queuecontroller.resources }}
      resources:
        {{- toYaml .Values.queuecontroller.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.queuecontroller.affinity }}
      affinity:
        {{- toYaml .Values.queuecontroller.affinity | nindent 8 }}
      {{- end }}

  admission:
    service:
      enabled: true
      image:
        name: {{ .Values.admission.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.admission.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.admission.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.admission.resources }}
      resources:
        {{- toYaml .Values.admission.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.admission.affinity }}
      affinity:
        {{- toYaml .Values.admission.affinity | nindent 8 }}
      {{- end }}
    gpuSharing: {{ .Values.global.gpuSharing | default false }}
    queueLabelSelector: false
    webhook:
      port: 443
      targetPort: {{ .Values.admission.ports.webhookPort | default 9443 }}
      probePort: {{ .Values.admission.ports.probePort | default 8081 }}
      metricsPort: {{ .Values.admission.ports.metricsPort | default 8080 }}
    gpuPodRuntimeClassName: {{ .Values.admission.gpuPodRuntimeClassName | default "nvidia" }}

  nodeScaleAdjuster:
    service:
      enabled: {{ .Values.global.clusterAutoscaling }}
      image:
        name: {{ .Values.nodescaleadjuster.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.nodescaleadjuster.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.nodescaleadjuster.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.nodescaleadjuster.resources }}
      resources:
        {{- toYaml .Values.nodescaleadjuster.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.nodescaleadjuster.affinity }}
      affinity:
        {{- toYaml .Values.nodescaleadjuster.affinity | nindent 8 }}
      {{- end }}
    args:
      nodeScaleNamespace: {{ .Values.nodescaleadjuster.scalingPodNamespace }}
      scalingPodImage:
        name: {{ .Values.nodescaleadjuster.scalingPodImage.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.nodescaleadjuster.scalingPodImage.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.nodescaleadjuster.scalingPodImage.pullPolicy | default .Values.global.imagePullPolicy }}

  scheduler:
    service:
      image:
        name: {{ .Values.scheduler.image.name }}
        repository: {{ .Values.global.registry }}
        tag: {{ .Values.scheduler.image.tag | default .Values.global.tag | default .Chart.AppVersion }}
        pullPolicy: {{ .Values.scheduler.image.pullPolicy | default .Values.global.imagePullPolicy }}
      {{- if .Values.scheduler.resources }}
      resources:
        {{- toYaml .Values.scheduler.resources | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.affinity }}
      affinity:
        {{- toYaml .Values.scheduler.affinity | nindent 8 }}
      {{- end }}
    {{- if and .Values.scheduler.ports .Values.scheduler.ports.metricsPort }}
    schedulerService:
      port: {{ .Values.scheduler.ports.metricsPort }}
    {{- end }}
