apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-csi-cluster
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-csi-cluster-binding
roleRef:
  kind: ClusterRole
  name: kubevirt-csi-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range .Values.deployment.namespaces }}
- kind: ServiceAccount
  name: kubevirt-csi
  namespace: {{ . | quote }}
{{- end }}  