---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevious-mysql.config" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-mysql.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
data:
  MYSQL_HOST: "{{ include "kubevious-mysql.host" . }}"
  MYSQL_PORT: "{{ include "kubevious-mysql.port" . }}"
  MYSQL_DB: "{{ include "kubevious-mysql.database" . }}"
  MYSQL_USER: "{{ include "kubevious-mysql.user" . }}"