{{- if not .Values.mysql.external.enabled -}}
---
{{- if .Values.mysql.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevious-mysql.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-mysql.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
  {{- with .Values.mysql.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}