{{- if .Values.secrets.create }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-secret-pre-install"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
    spec:
      serviceAccountName: {{ template "opsportal.fullname" . }}-temp
      restartPolicy: Never
      containers:
        - name: "{{.Release.Name}}-pre-install"
          image: "{{.Values.secrets.image.repository}}:{{.Values.secrets.image.tag}}"
          args:
            - opsportal-secret
            - create
            - --name={{ .Values.secrets.name }}
            - --namespace={{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-secret-post-delete"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
    spec:
      serviceAccountName: {{ template "opsportal.fullname" . }}-temp
      restartPolicy: Never
      containers:
      - name: "{{.Release.Name}}-post-delete"
        image: "{{.Values.secrets.image.repository}}:{{.Values.secrets.image.tag}}"
        args:
        - opsportal-secret
        - delete
        - --name={{ .Values.secrets.name }}
        - --namespace={{ .Release.Namespace }}
{{- end }}
