# spectrocloud.com/enabled-presets:
pack:
  content:
    images:
      - image: quay.io/piraeusdatastore/piraeus-operator:v2.9.0
      - image: quay.io/piraeusdatastore/piraeus-server:v1.31.2
      - image: quay.io/piraeusdatastore/piraeus-csi:v1.8.0
      - image: quay.io/piraeusdatastore/drbd-reactor:v1.8.0
      - image: quay.io/piraeusdatastore/piraeus-ha-controller:v1.3.0
      - image: quay.io/piraeusdatastore/drbd-shutdown-guard:v1.0.0
      - image: quay.io/piraeusdatastore/ktls-utils:v1.1.0
      - image: quay.io/piraeusdatastore/drbd9-centos7:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-almalinux8:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-almalinux9:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-bionic:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-focal:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-jammy:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-noble:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-bookworm:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-bullseye:v9.2.14
      - image: quay.io/piraeusdatastore/drbd9-buster:v9.2.14
      - image: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
      - image: registry.k8s.io/sig-storage/livenessprobe:v2.16.0
      - image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
      - image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
      - image: registry.k8s.io/sig-storage/csi-resizer:v1.13.2
      - image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.15.0
      - image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.14.0
      - image: us-docker.pkg.dev/palette-images/packs/csi-piraeus-operator/2.8.1/linstor-gui:v1.9.5
      - image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
  namespace: piraeus-system
  namespaceLabels:
    "piraeus-system": "pod-security.kubernetes.io/enforce=privileged,pod-security.kubernetes.io/enforce-version=v{{ .spectro.system.kubernetes.version | substr 0 4 }}"

readinessCheck:
  v1beta1:
    - name: "linstorcluster"
      kind: "LinstorCluster"
      group: "piraeus.io"
      version: "v1"
      keysToCheck:
      - keyToCheck: "status.conditions[0].status"
        expectedValue: "True"
      - keyToCheck: "status.conditions[1].status"
        expectedValue: "True"
      - keyToCheck: "status.conditions[2].status"
        expectedValue: "True"

charts:
  piraeus-cluster:
    cluster:
      masterPassphrase:
        # Leave empty to auto-generate
        value: ""
      spec:
        linstorPassphraseSecret: linstor-passphrase
        # Set nodeAffinity or nodeSelector to control where Piraeus runs
        # nodeAffinity:
        #   nodeSelectorTerms:
        #     - matchExpressions:
        #         - key: node-role.kubernetes.io/control-plane
        #           operator: DoesNotExist

        # If you need to pull images from a different registry, enable and set the "repository" parameter below.
        # Note that if the repository setting is enabled, the images from registry.k8s.io for Piraeus (lines 34-40 above)
        # will also be pulled from your custom registry instead. Make sure you have those images on your registry.
        # repository: registry.example.com/piraeus-mirror

    linstorSatelliteConfigurations:
      - name: host-network
        spec:
          podTemplate:
            spec:
              hostNetwork: true
      - name: lvm-thin-storage-pool
        spec:
          storagePools:
            - name: lvm-thin
              lvmThinPool:
                volumeGroup: drbd-vg
                thinPool: thinpool
              source:
                hostDevices:
                  - /dev/sdb
      # - name: http-proxy
      #   spec:
      #     podTemplate:
      #       spec:
      #         initContainers:
      #           - name: drbd-module-loader
      #             env:
      #               - name: HTTP_PROXY
      #                 value: http://10.0.0.1:3128 # Add your proxy connection here
      #               - name: HTTPS_PROXY
      #                 value: http://10.0.0.1:3128 # Add your proxy connection here
      #               - name: NO_PROXY
      #                 value: localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12 # Add internal IP ranges and domains here

    linstorNodeConnections: []
      # - name: network-paths
      #   spec:
      #     paths:
      #       - name: path1
      #         interface: data-nic

    storageClasses:
      - name: linstor-lvm-storage
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
          #storageclass.kubevirt.io/is-default-virt-class: "true"
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: WaitForFirstConsumer
        parameters:
          placementCount: "2"
          storagePool: "lvm-thin"
          resourceGroup: "lvm"
          #replicasOnDifferent: topology.kubernetes.io/zone
          #DrbdOptions/Net/allow-two-primaries: "yes"
          #allowRemoteVolumeAccess: "false"
          #DrbdOptions/Disk/disk-flushes: "no"
          #DrbdOptions/Disk/md-flushes: "no"
          #DrbdOptions/Disk/al-extents: "65534"
          #DrbdOptions/Net/max-buffers: "10000"
          #DrbdOptions/Net/max-epoch-size: "10000"
          #DrbdOptions/Net/sndbuf-size: "0"

    monitoring:
      # Ensure Prometheus (Agent) is installed before or at the same time as this pack when enabling this option
      installPrometheusRules: false

  piraeus:
    replicaCount: 1
    installCRDs: true
    operator:
      image:
        repository: quay.io/piraeusdatastore/piraeus-operator
        pullPolicy: IfNotPresent
        # Overrides the image tag whose default is the chart appVersion.
        tag: ""
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      options:
        leaderElect: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 64Mi
    kubeRbacProxy:
      enabled: false
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        pullPolicy: IfNotPresent
        tag: v0.13.1
      options:
        logtostderr: "true"
        v: 0
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      resources: { }
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
    webhook:
      timeoutSeconds: 2
      failurePolicy: Fail
    tls:
      certificateSecret: ""
      autogenerate: true
      renew: false
      certManagerIssuerRef: {}
    imagePullSecrets: [ ]
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: { }
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""
    rbac:
      # Specifies whether RBAC resources should be created
      create: true
    podAnnotations: { }
    podSecurityContext: {}
      # fsGroup: 2000
    nodeSelector: { }
    tolerations:
      - key: drbd.linbit.com/lost-quorum
        effect: NoSchedule
      - key: drbd.linbit.com/force-io-error
        effect: NoSchedule
    affinity: { }
    priorityClassName: ""
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      # maxUnavailable: 1
    imageConfigOverride: []
      # - base: example.com/piraeus
      #   components:
      #     linstor-csi:
      #       image: linstor-csi
      #       tag: my-custom-tag
      #   Results in the image example.com/piraeus/linstor-csi:my-custom-tag being used.
      #   See templates/config.yaml for available components.
  piraeus-dashboard:
    # Ensure Grafana is installed before or at the same time as this pack when enabling this option
    installPiraeusDashboard: false
    namespace: piraeus-system

  linstor-gui:
    enabled: true
    image:
      repository: us-docker.pkg.dev/palette-images/packs/csi-piraeus-operator/2.8.1/linstor-gui
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v1.9.5"
    replicas: 1
    service:
      type: NodePort
      nodePort: 30337
      # Ensure a LoadBalancer pack is installed before or at the same time as this pack when using the LoadBalancer type
      # type: LoadBalancer
      # port: 8000
    apiHost: "http://linstor-controller.piraeus-system.svc.cluster.local:3370"