{{- if .Values.oauth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appdynamics-smartagent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appdynamics-smartagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  OAUTH_SECRET: {{ .Values.oauth.clientSecret | quote }}
{{- end }}