---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubevious-mysql.fullname" . }}-init-script
  labels:
    app.kubernetes.io/component: {{ include "kubevious-mysql.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
data:
  initdb.sql: |
    USE kubevious;

    SET NAMES utf8;