apiVersion: v2
appVersion: 24.2.0
description: Helm chart for Appdynamics Cloud Operator
home: https://appdynamics.com
icon: https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png
keywords:
- appdynamics
- operator
- cluster
- kubernetes
- monitoring
- pod
- deployment
maintainers:
- email: support@appdynamics.com
  name: AppDynamics
name: appdynamics-cloud-operator
version: 1.19.0
