{{ if and .Values.install.defaultInfraCollectors (has "linux" .Values.servermonConfig.os) -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: Servermon
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-servermon" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
spec:
  os: linux
  {{$servermonConfig := .Values.servermonConfig}}
  {{ if (.Values.servermonConfig.env).linux -}}
  {{$servermonConfig = mustMergeOverwrite .Values.servermonConfig .Values.servermonConfig.env.linux}}
  {{- end }}
  {{ with $servermonConfig -}}
  {{ if .gatherInterval -}}
  gatherInterval: {{ .gatherInterval }}
  {{- end }}
  logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
  logFilesNumBackups: {{ .logFilesNumBackups }}
  logLevel: {{ .logLevel }}

  {{ if .skipProviderCheck -}}
  skipProviderCheck: {{ .skipProviderCheck | quote }}
  {{- end }}

  {{ if .exporterPort -}}
  exporterPort: {{ .exporterPort }}
  {{- end }}

  {{- end }}
{{- end }}
---
{{ if and .Values.install.defaultInfraCollectors (has "windows" .Values.servermonConfig.os) -}}
apiVersion: cluster.appdynamics.com/v1alpha1
kind: Servermon
metadata:
  name: {{ printf "%s-%s" .Release.Name "appdynamics-servermon-windows" | trunc 63 }}
  namespace: {{ .Release.Namespace }}
spec:
  os: windows
  {{$servermonConfig := .Values.servermonConfig}}
  {{ if (.Values.servermonConfig.env).windows -}}
  {{$servermonConfig = mustMergeOverwrite .Values.servermonConfig .Values.servermonConfig.env.windows}}
  {{- end }}
  {{ with $servermonConfig -}}
  {{ if .gatherInterval -}}
  gatherInterval: {{ .gatherInterval }}
  {{- end }}
  logFilesMaxSizeMb: {{ .logFilesMaxSizeMb }}
  logFilesNumBackups: {{ .logFilesNumBackups }}
  logLevel: {{ .logLevel }}

  {{ if .skipProviderCheck -}}
  skipProviderCheck: {{ .skipProviderCheck | quote }}
  {{- end }}

  {{ if .exporterPort -}}
  exporterPort: {{ .exporterPort }}
  {{- end }}

  {{- end }}
{{- end }}