apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.spec.linstorPassphraseSecret }}
  namespace: piraeus-system
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MASTER_PASSPHRASE: {{ default (randAlphaNum 20) .Values.cluster.masterPassphrase.value | b64enc | quote }}