operatorServiceAccount: appdynamics-cloud-operator
enableOTelCRDManagement: true
watchMode: namespace
operatorPod:
  image: appdynamics/appdynamics-cloud-operator:24.1.0-1230
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}
  priorityClassName: null
kubeRbacProxy: {}

testFramework:
  # Can be used to disable rendering test resources when using helm template
  enabled: true
  image:
    repository: busybox
    tag: latest
