apiVersion: v2
description: AutoOps Agent Policy managed by the ECK operator
kubeVersion: '>= 1.21.0-0'
name: eck-autoops-agent-policy
sources:
- https://github.com/elastic/cloud-on-k8s
type: application
version: 0.18.0
