# spectrocloud.com/enabled-presets: Backend:disable-api

pack:
  content:
    images:
      - image: ghcr.io/spectrocloud/hello-universe:1.1.2


manifests:
  hello-universe:
    images:
      hellouniverse: ghcr.io/spectrocloud/hello-universe:1.1.2
    namespace: "hello-universe"
    port: 8080
    replicas: 1
