apiVersion: v2
appVersion: 24.3.0
description: Helm Chart to deploy clustermon as a deployment and infra manager, containermon,
  servermon, log collector as a daemonset.
home: https://appdynamics.com
icon: https://raw.githubusercontent.com/CiscoDevNet/appdynamics-charts/master/logo.png
keywords:
- appdynamics
- cluster
- kubernetes
- monitoring
- pod
- deployment
maintainers:
- email: support@appdynamics.com
  name: AppDynamics
name: appdynamics-cloud-k8s-monitoring
version: 1.20.0
