apiVersion: v2
description: Elastic APM Server managed by the ECK operator
icon: https://helm.elastic.co/icons/apm.png
kubeVersion: '>= 1.21.0-0'
name: eck-apm-server
sources:
- https://github.com/elastic/cloud-on-k8s
- https://github.com/elastic/apm-server
type: application
version: 0.16.0
