apiVersion: v1
appVersion: 1.0.0
description: A Kubernetes operator that simplifies the management of Role Bindings
  and Service Accounts.
home: https://fairwindsops.github.io/rbac-manager/
icon: https://raw.githubusercontent.com/FairwindsOps/charts/master/stable/rbac-manager/icon.png
keywords:
- rbac
- authorization
maintainers:
- email: andy@fairwinds.com
  name: sudermanjr
- email: luke@fairwinds.com
  name: lucasreed
name: rbac-manager
sources:
- https://github.com/FairwindsOps/charts/tree/master/stable/rbac-manager
- https://github.com/FairwindsOps/rbac-manager
version: 1.9.0
