apiVersion: v2
description: Elastic Package Registry managed by the ECK operator
kubeVersion: '>= 1.21.0-0'
name: eck-package-registry
sources:
- https://github.com/elastic/cloud-on-k8s
- https://github.com/elastic/package-registry
type: application
version: 0.18.0
