pack:
  content:
    images:
      - image: quay.io/dell/container-storage-modules/dell-csm-operator:v1.9.1
      - image: quay.io/dell/container-storage-modules/csi-isilon:v2.14.0
      - image: quay.io/dell/container-storage-modules/csi-powermax:v2.14.1
      - image: quay.io/dell/container-storage-modules/csipowermax-reverseproxy:v2.13.1
      - image: quay.io/dell/container-storage-modules/csi-powerstore:v2.14.1
      - image: quay.io/dell/container-storage-modules/csi-unity:v2.14.0
      - image: quay.io/dell/container-storage-modules/csi-vxflexos:v2.14.1
      - image: quay.io/dell/storage/powerflex/sdc:4.5.4
      - image: quay.io/dell/container-storage-modules/csm-authorization-sidecar:v2.2.0
      - image: quay.io/dell/container-storage-modules/csm-authorization-proxy:v2.2.0
      - image: quay.io/dell/container-storage-modules/csm-authorization-tenant:v2.2.0
      - image: quay.io/dell/container-storage-modules/csm-authorization-role:v2.2.0
      - image: quay.io/dell/container-storage-modules/csm-authorization-storage:v2.2.0
      - image: quay.io/dell/container-storage-modules/csm-authorization-controller:v2.2.0
      - image: quay.io/dell/container-storage-modules/dell-csi-replicator:v1.12.0
      - image: quay.io/dell/container-storage-modules/dell-replication-controller:v1.12.0
      - image: quay.io/dell/container-storage-modules/csm-topology:v1.12.0
      - image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.124.0
      - image: quay.io/dell/container-storage-modules/csm-metrics-powerscale:v1.9.0
      - image: quay.io/dell/container-storage-modules/csm-metrics-powermax:v1.7.0
      - image: quay.io/dell/container-storage-modules/csm-metrics-powerflex:v1.12.0
      - image: quay.io/dell/container-storage-modules/podmon:v1.13.0
      - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.16.0-202409051837.p0.g8ea2c99.assembly.stream.el9
      - image: registry.k8s.io/sig-storage/csi-attacher:v4.8.0
      - image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
      - image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
      - image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
      - image: registry.k8s.io/sig-storage/csi-resizer:v1.13.1
      - image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.14.0
      - image: quay.io/dell/container-storage-modules/csi-metadata-retriever:v1.10.0

charts:
  csm-operator:
    namespace: dell-csm-operator

    image:
      repository: quay.io/dell/container-storage-modules/dell-csm-operator
      pullPolicy: IfNotPresent
      tag: "v1.9.1"

    csm:
      # Select a preset to populate the default configuration for your platform