apiVersion: v1
appVersion: 1.4.3
description: Collect Kubernetes objects with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-objects
keywords:
- splunk
- monitoring
- objects
- metadata
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-kubernetes-objects
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-objects
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-objects
version: 1.4.3
