apiVersion: v2
appVersion: 25.10.0
description: A Helm chart for deploying NetApp's Trident CSI storage provisioner using
  the Trident Operator.
home: https://github.com/NetApp/trident
icon: https://raw.githubusercontent.com/NetApp/trident/master/logo/trident.png
keywords:
- NetApp
- Trident
- operator
- CSI
kubeVersion: '>= 1.24.0-0'
name: trident-operator
type: application
version: 100.2510.0
