---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevious-parser.fullname" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevious-parser.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubevious-parser.fullname" . }}
  namespace: {{ .Release.Namespace }}