apiVersion: v1
appVersion: 1.4.3
description: Collect logs, objects (metadata), and metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart
keywords:
- splunk
- monitoring
- logging
- metrics
- metadata
- objects
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-connect-for-kubernetes
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-objects
version: 1.4.3
