---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: weka-operator
  name: "{{ .Values.prefix }}-manager-rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.prefix }}-manager-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.prefix }}-controller-manager"
    namespace: "{{ .Release.Namespace }}"
