apiVersion: v1
kind: ConfigMap
metadata:
  name: weka-boot-scripts
data:
  syslog-ng.conf: |
{{ .Files.Get "resources/syslog-ng.conf" | indent 4 }}
  run-weka-cli.sh: |
{{ .Files.Get "resources/run-weka-cli.sh" | indent 4 }}
  weka_runtime.py: |
{{ .Files.Get "resources/weka_runtime.py" | indent 4 }}
  devenv.sh: |
{{ .Files.Get "resources/cos-devenv.sh" | indent 4 }}
