pack:
  content:
    images:
      - image: quay.io/dell/container-storage-modules/dell-csm-operator:v1.11.0 
      - image: quay.io/dell/container-storage-modules/csi-isilon:v2.16.0 
      - image: quay.io/dell/container-storage-modules/csi-powermax:v2.16.0 
      - image: quay.io/dell/container-storage-modules/csipowermax-reverseproxy:v2.15.0 
      - image: quay.io/dell/container-storage-modules/csi-powerstore:v2.16.0 
      - image: quay.io/dell/container-storage-modules/csi-unity:v2.16.0 
      - image: quay.io/dell/container-storage-modules/csi-vxflexos:v2.16.0 
      - iamge: quay.io/dell/container-storage-modules/cosi:v1.0.0 
      - image: quay.io/dell/storage/powerflex/sdc:5.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-sidecar:v2.4.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-proxy:v2.4.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-tenant:v2.4.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-role:v2.4.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-storage:v2.4.0 
      - image: quay.io/dell/container-storage-modules/csm-authorization-controller:v2.4.0 
      - image: quay.io/dell/container-storage-modules/dell-csi-replicator:v1.14.0 
      - image: quay.io/dell/container-storage-modules/dell-replication-controller:v1.14.0 
      - image: quay.io/dell/container-storage-modules/csm-topology:v1.12.0
      - image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.143.1 
      - image: quay.io/dell/container-storage-modules/csm-metrics-powerscale:v1.11.0 
      - image: quay.io/dell/container-storage-modules/csm-metrics-powermax:v1.9.0 
      - image: quay.io/dell/container-storage-modules/csm-metrics-powerflex:v1.14.0
      - image: quay.io/dell/container-storage-modules/csm-metrics-powerstore:v1.14.0
      - image: quay.io/dell/container-storage-modules/podmon:v1.15.0 
      - image: quay.io/nginx/nginx-unprivileged:1.27 
      - image: registry.k8s.io/sig-storage/csi-attacher:v4.10.0 
      - image: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0 
      - image: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0 
      - image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0 
      - image: registry.k8s.io/sig-storage/csi-resizer:v1.13.1 
      - image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.14.0 
      - image: quay.io/dell/container-storage-modules/csi-metadata-retriever:v1.11.0 

charts:
  csm-operator:
    namespace: dell-csm-operator

    image:
      repository: quay.io/dell/container-storage-modules/dell-csm-operator
      pullPolicy: IfNotPresent
      tag: "v1.16.0"

    # Resources for the operator deployment. The Operator might need more resources if the environment is large (more than 1000 pods)
    # https://dell.github.io/csm-docs/docs/getting-started/installation/operator/operatorinstallation_kubernetes/
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 192Mi

    csm:
      # Select a preset to populate the default configuration for your platform