apiVersion: v1
appVersion: 1.4.3
description: Collect metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-metrics
keywords:
- splunk
- monitoring
- metric
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-kubernetes-metrics
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-splunk-hec
version: 1.4.3
