apiVersion: v1
appVersion: 1.4.3
description: Collect logs with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-logging
keywords:
- splunk
- monitoring
- logging
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-kubernetes-logging
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-logging
- https://github.com/splunk/fluent-plugin-splunk-hec
version: 1.4.3
