# cluster role that allowed to perform describe ("get") over ["nodes"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: weka-operator
  name: "{{ .Values.prefix }}-node-describe-role"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
