apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-driver-toolkit-images
data:
  414.92.202404162000-0: "259cbd840454c6d9030c21a5d24be0599abc4941cdd525a80f6eeb5d67e7908c"
  414.92.202404231906-0: "20dce872df7c233a34179b4356acc1c6cbd80c56cff053fa437de3b6595f9710"
  414.92.202404301839-0: "20dce872df7c233a34179b4356acc1c6cbd80c56cff053fa437de3b6595f9710"
  415.92.202402201450-0: "cd0ea5d8ec43c5b03bf362e0b595bafe3e97e222d4344a851453ebe8770df135"
  415.92.202403061641-0: "9d974e00ebe924fbd03abf03c55d873108a1593b5a5e60f0daf4b867fc5bb1b1"
  415.92.202403080220-0: "9d974e00ebe924fbd03abf03c55d873108a1593b5a5e60f0daf4b867fc5bb1b1"
  415.92.202403191241-0: "abbff60a77f7ac2276dbeef33fb46ed32c9b9eb1c5813260c6383605bed76a08"
  415.92.202403270524-0: "b9cd86347ba410c90b4a34fe9c1b25951e0f0cd38ceca1d3ccd4bae96f084edb"
  415.92.202404161628-0: "be818782c507d76b48f9f37bcf85e5d5311514ff9e6108b047f80bf6331e63f5"
  415.92.202404251009-0: "bae8035c05d095e84c62efcab6202330a98493cab03e091c81a0b792afb5672c"
  415.92.202404302054-0: "bae8035c05d095e84c62efcab6202330a98493cab03e091c81a0b792afb5672c"
  415.92.202405070140-0: "985b72435a7091702a520581eb51ebd439bfe6ff39c33ffaaad7e30b9e321454"
  415.92.202405130844-0: "985b72435a7091702a520581eb51ebd439bfe6ff39c33ffaaad7e30b9e321454"
  415.92.202405201956-0: "934af754e2fbc8ed5deb7c4b22299c6c7b4504e6d8d9fd50fc3ad374616d70a9"
  415.92.202405281402-0: "d493e0bd8959e0d117493453db9c183e8bca34f73eb89b091134a087554fa0e8"
  415.92.202406041802-0: "9d2c61bf746c966f71bc6c6a3797303a7d3bfaef09040dfde85f19383d19681b"
  415.92.202406111137-0: "efa99ae171e7db22aa2d320b7bc78e950db01987889b6a8529e1945670e80792"
  416.94.202406172220-0: "dde3cd6a75d865a476aa7e1cab6fa8d97742401e87e0d514f3042c3a881e301f"
  416.94.202406251923-0: "8ef92caba7bd5d6ab3a139da782bf5651c2a40802eaa33b0c7899a7e897e007b"
  416.94.202407030122-0: "e5e6de7572003ac560f113a0082594a585c49d51801f028f699b15262eff7c02"
  416.94.202407081958-0: "a73204d0c03454b02656801ca4c49cb2d8b0d54645bb90f74622df335c82dce1"