{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: {{ .Values.prefix }}-maintenance-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostPID: true
allowHostNetwork: true
allowedVolumeTypes:
  - hostPath
  - secret
readOnlyRootFilesystem: false
allowHostPorts: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.prefix }}-maintenance
{{- end }}
