pack:
  releaseNameOverride:
      dpf-deployment: dpf-deployment
  namespace: dpf-operator-system
  content:
    images: []

charts:
  dpf-deployment:
    bfb: {}
    dpuFlavors: []
    dpuSets: []
    dpuServices: []
    dpuServiceChains: []
    dpuServiceConfigurations: []
    dpuDeployments: []
    dpuServiceTemplates: []
    dpuServiceInterfaces: []
    dpuServiceCredentialRequests: []
    dpuServiceIPAMs: []
  # Please select a preset to populate a starting configuration